import "./globals.css";
import { Analytics } from "@vercel/analytics/react";


export const metadata = {
  title: "Clock",
  description: "Definately Not Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
